menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name = "list"),
    url(r'^create/$', ItemCreateView.as_view(), name = "create"),
    # url(r'^(?P<pk>\d+)/edit$', ItemUpdateView.as_view(), name = 'update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name = 'detail'),
]

muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import LoginView, LogoutView

from django.views.generic import TemplateView

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),   
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/',ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name="contact"),
]

restaurants/urls.py
from django.conf.urls import url

from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name = "list"),
    url(r'^create/$', RestaurantCreateView.as_view(), name = "create"),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name = 'detail'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name = 'update'),
]

restaurants/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse
from django.db.models import Q

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query): #RestaurantLocation.objects.all().search(query)
        if query:
            return self.filter(
                Q(name__icontains=query)|
                Q(location__icontains=query)|
                Q(category__icontains=query)|
                Q(item__name__icontains=query)|
                Q(item__contents__icontains=query)
            ).distinct()
        return self

class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query): #RestaurantLocation.objects.search(query)
        return self.get_queryset().search(query)

class RestaurantLocation(models.Model):
    owner          = models.ForeignKey(User)
    name          = models.CharField(max_length = 120)
    location      = models.CharField(max_length = 120, null = True, blank = True)
    category      = models.CharField(max_length = 120, null = True, blank = True, validators = [validate_category])
    timestamp     = models.DateTimeField(auto_now_add = True)
    updated       = models.DateTimeField(auto_now = True)
    slug          = models.SlugField(null = True, blank = True)
    #my_date_field = models.DateTimeField(auto_now = False, auto_now_add = False)

    objects = RestaurantLocationManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return f"restaurants/{self.slug}"
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

# def rl_post_save_receiver(sender, instance, *args, **kwargs):
#     print('saved')
#     print(instance.timestamp)
#     if not instance.slug:
#     instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender = RestaurantLocation)
# post_save.connect(rl_post_save_receiver, sender = RestaurantLocation)

restaurants/forms.py
from django import forms

from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form):
    name          = forms.CharField()
    location      = forms.CharField(required = False)
    category      = forms.CharField(required = False)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name

class RestaurantLocationCreateForm(forms.ModelForm):
    # email = forms.EmailField()
    # category = forms.CharField(required = False, validators = [validate_category])
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug'
        ]

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name
    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     if ".edu" in email:
    #         raise forms.ValidationError("We do not accept edu emails")
    #     return email

restaurants/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView

from .models import RestaurantLocation
from .forms import RestaurantCreateForm, RestaurantLocationCreateForm

class RestaurantListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    # def get_object(self, *args, **kwargs):
    #     rest_id = self.kwargs.get('rest_id')
    #     obj = get_object_or_404(RestaurantLocation, id = rest_id)
    #     return obj

class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    # login_url = '/login/'
    template_name = 'form.html'
    # success_url = '/restaurants/'

    def form_valid(self, form):
        instance = form.save(commit = False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    # login_url = '/login/'
    template_name = 'restaurants/detail-update.html'
    # success_url = '/restaurants/'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.title }} || Restaurants || {{ block.super }}{% endblock %}

{% block content %}

<h1>{{ form.instance.name }} <small>{{ form.instance.category }}</small>  </h1>
<p>{{ form.instance.location }}</p>
<p>{{ form.instance.timestamp }}, Updated {{ form.instance.updated|timesince}} ago</p>

<hr/>
<h3>Make changes</h3>
{% include 'snippets/form_snippet.html' with form=form %}

{% endblock content %}

restaurants/templates/restaurants/form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} || {{ block.super }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="button">Save</button>
</form>
{% endblock content %}
<!-- <input type="text" name="name" placeholder="Your Title..."> <br/>
<input type="text" name="location" placeholder="Your Location..."> <br/>
<input type="text" name="category" placeholder="Your Category..."> <br/> -->

restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super }}{% endblock %}

{% block content %}

<h1>{{ object.name }} <small>{{ object.category }}</small>  </h1>
<p>{{ object.location }}</p>
<p>{{ object.timestamp }}, Updated {{ object.updated|timesince}} ago</p>
{% endblock content %}

restaurants/templates/restaurants/restaurantlocation_list.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super }}{% endblock %}

{% block content %}
<h1>My Restaurants <small><a href="{% url 'restaurants:create' %}">Add New</a></small> </h1>
{% for obj in object_list %}
    <li>
        <a href="{{ obj.get_absolute_url }}">{{ obj }}</a>
        <br/>
        {{ obj.name }} {{ obj.location }} {{ obj.category }} {{ obj.timestamp }} {{ obj.updated }}
    </li>
{% empty %}
<li><a href="{% url 'restaurants:create' %}">Add One</a></li>
{% endfor %}
{% endblock content %}