menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name = "list"),
    url(r'^create/$', ItemCreateView.as_view(), name = "create"),
    # url(r'^(?P<pk>\d+)/edit$', ItemUpdateView.as_view(), name = 'update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name = 'detail'),
]

muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import LoginView, LogoutView

from django.views.generic import TemplateView

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),   
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/',ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name="contact"),
]

templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

templates/snippets/form_snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="button">Save</button>
</form>

templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class="container">
    <h1>MuyPick.com</h1>
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'about' %}">About</a>
    <a href="{% url 'contact' %}">Contact</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'restaurants:list' %}">Restaurants</a>
    <a href="{% url 'menus:list' %}">Menu Items</a>
    {% endif %}
</div>